modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "defaulted"
version = "${version}"
displayName = "Defaulted"
authors = "Alexandra"
description = '''
Minecraft mod to enable in-game modification of default item components.
'''
logoFile = "assets/icon.png"

[[dependencies.defaulted]]
modId = "neoforge"
type = "required"
versionRange = "[20.5.21-beta,21.0)"
ordering = "NONE"
side = "BOTH"

[[dependencies.defaulted]]
modId = "minecraft"
type = "required"
versionRange = "[1.20.5,1.21)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "defaulted.mixins.json"

[[mixins]]
config = "defaulted-neoforge.mixins.json"
