modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "CC0-1.0"

[[mods]]
modId = "defaulted"
version = "${version}"
displayName = "Defaulted"
authors = "Alexandra"
description = '''
Minecraft mod to enable in-game modification of default item components.
'''
logoFile = "assets/icon.png"

[[dependencies.defaulted]]
modId = "neoforge"
type = "required"
versionRange = "[21.1.131,21.2)"
ordering = "NONE"
side = "BOTH"

[[dependencies.defaulted]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,1.21.2)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "defaulted.mixins.json"

[[mixins]]
config = "defaulted-neoforge.mixins.json"
