modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "defaulted"
version = "${version}"
displayName = "Defaulted"
authors = "Alexandra"
description = '''
Minecraft mod to enable in-game modification of default item components.
'''
logoFile = "assets/icon.png"

[[dependencies.defaulted]]
modId = "neoforge"
type = "required"
versionRange = "[21.5.65-beta,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.defaulted]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.5,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "defaulted.mixins.json"
